"""
08/03/2022

Q: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

A:4613732

"""

# Find the Fibonacci sequence
x = 1
y = 2
z = 0
nums = [1,2]

while z < 4_000_000:
    z = x + y
    x = y
    y = z
    if z < 4_000_000:
        nums.append(z)

# Extract only the positive values
pos_nums = []
for i in nums:
    if i%2 == 0:
        pos_nums.append(i)

print(sum(pos_nums))

