'''
9/27/2022

Q: Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

A: 1533776805

'''

# Create lists of pent and hex numbers
pentNums = []
hexNums = []
for i in range(1, 100_000):
    pentNums.append(int((i*((3*i)-1))/2))
    hexNums.append(int(i*((2*i)-1)))

# Loop through until a match is found for both - skip 40755
# Be ready this program is not optimized, so it takes a bit to run
for i in range(2,100_000):
    triNum = int((i*(i+1))/2)
    if triNum in pentNums and triNum in hexNums:
        if triNum != 40755:
            print(triNum)
            break